- pom.xml
> upgrade polaris-java version

- .github/workflows/maven-publish.yml
- polaris-agent-adapter/pinpoint/pinpoint-bootstrap/pom.xml
- polaris-agent-bootstrap/src/main/java/cn/polarismesh/agent/bootstrap/JavaAgentPathResolver.java
- polaris-agent-build/bin/build-pinpoint.sh
- polaris-agent-build/bin/plugins
- polaris-agent-core/common/common-polaris/src/test/java/com/polarismesh/common/polaris/PolarisOperatorTest.java
- polaris-agent-core/plugins/nacosv1/src/main/java/cn/polarismesh/agent/core/nacos/v1/constants/NacosConstants.java
- polaris-agent-core/plugins/nacosv1/src/main/java/cn/polarismesh/agent/core/nacos/v1/delegate/NacosV1NamingProxy.java
- polaris-agent-core/plugins/nacosv1/src/main/java/cn/polarismesh/agent/core/nacos/v1/interceptor/NacosV1NamingFactoryInterceptor.java
- polaris-agent-examples/dubbo2/README-zh.md
- polaris-agent-examples/dubbo2/README.md
- polaris-agent-examples/dubbox/README-zh.md
- polaris-agent-examples/dubbox/README.md
- pom.xml
Fixes #
支持nacos1.3.1客户端版本双注册和发现
> 支持nacos1.3.1客户端版本双注册和发现

- .github/workflows/maven-publish.yml
- polaris-agent-adapter/pinpoint/pinpoint-bootstrap/pom.xml
- polaris-agent-bootstrap/src/main/java/cn/polarismesh/agent/bootstrap/JavaAgentPathResolver.java
- polaris-agent-build/bin/build-pinpoint.sh
- polaris-agent-build/bin/plugins
- polaris-agent-core/common/common-polaris/src/test/java/com/polarismesh/common/polaris/PolarisOperatorTest.java
- polaris-agent-examples/dubbo2/README-zh.md
- polaris-agent-examples/dubbo2/README.md
- polaris-agent-examples/dubbox/README-zh.md
- polaris-agent-examples/dubbox/README.md
- pom.xml
> 调整dubbox-2.x分支插件打包内容

- .github/workflows/maven-publish.yml
- polaris-agent-adapter/pinpoint/pinpoint-bootstrap/pom.xml
- polaris-agent-bootstrap/src/main/java/cn/polarismesh/agent/bootstrap/JavaAgentPathResolver.java
- polaris-agent-build/bin/build-pinpoint.sh
- polaris-agent-build/bin/plugins
- polaris-agent-core/common/common-polaris/src/test/java/com/polarismesh/common/polaris/PolarisOperatorTest.java
- polaris-agent-examples/dubbo2/README-zh.md
- polaris-agent-examples/dubbo2/README.md
- polaris-agent-examples/dubbox/README-zh.md
- polaris-agent-examples/dubbox/README.md
- pom.xml
> 调整dubbo-2.x分支插件打包内容

- polaris-agent-core/plugins/nacosv1/src/main/java/cn/polarismesh/agent/core/nacos/v1/constants/NacosConstants.java
- polaris-agent-core/plugins/nacosv1/src/main/java/cn/polarismesh/agent/core/nacos/v1/delegate/NacosV1NamingProxy.java
- polaris-agent-core/plugins/nacosv1/src/main/java/cn/polarismesh/agent/core/nacos/v1/interceptor/NacosV1NamingFactoryInterceptor.java
- pom.xml
Fixes #84 
支持nacos1.3.0客户端版本双注册和发现的能力
> 支持nacos1.3.0客户端版本双注册和发现的能力

- polaris-agent-build/bin/build.sh
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2021-plugin/pom.xml
- pom.xml
> fix:添加SNAPSHOT拉取

- .github/workflows/maven-publish.yml
- polaris-agent-build/bin/build.sh
- polaris-agent-plugins/nacos-plugins/nacos-all-plugin/src/main/java/cn/polarismesh/agent/plugin/nacos/delegate/NamingProxyAssist.java
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2021-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/serviceregistry/RegistryInterceptor.java
> fix:修复nacos java-agent双注册双发现迁移

- polaris-agent-plugins/dubbo-plugins/dubbo2-plugin/pom.xml
- polaris-agent-plugins/dubbo-plugins/dubbo2-plugin/src/main/java/com/tencent/polaris/Main.java
- polaris-agent-plugins/dubbo-plugins/dubbox-plugin/pom.xml
- polaris-agent-plugins/dubbo-plugins/dubbox-plugin/src/main/java/com/tencent/polaris/Main.java
- polaris-agent-plugins/dubbo-plugins/pom.xml
- polaris-agent-plugins/pom.xml
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2020-plugin/src/main/conf/plugin/springcloud2020/application.properties
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2021-plugin/src/main/conf/plugin/springcloud2021/application.properties
> fix:修复配置模版

- .github/workflows/docker.yml
- .github/workflows/maven-publish.yml
- .gitignore
- polaris-agent-build/bin/build.sh
- polaris-agent-build/bin/build_docker.sh
- polaris-agent-core/polaris-agent-core-asm-java9/pom.xml
- polaris-agent-core/polaris-agent-core-asm-java9/src/main/java/cn/polarismesh/agent/core/asm9/instrument/BuiltinClassLoaderHandler.java
- polaris-agent-core/polaris-agent-core-asm-java9/src/main/java/cn/polarismesh/agent/core/asm9/instrument/Java9DefineClass.java
- polaris-agent-core/polaris-agent-core-asm-java9/src/main/java/cn/polarismesh/agent/core/asm9/instrument/JavaLangAccessHelper.java
- polaris-agent-core/polaris-agent-core-asm/src/main/java/cn/polarismesh/agent/core/asm/instrument/JavaLangAccess.java
- polaris-agent-core/polaris-agent-core-bootstrap/src/main/java/cn/polarismesh/agent/core/bootstrap/entry/BootStrap.java
- polaris-agent-core/polaris-agent-core-optional-java17/pom.xml
- polaris-agent-core/polaris-agent-core-optional-java17/src/main/java/cn/polarismesh/agent/core/optional17/instrument/JavaLangAccess17.java
- polaris-agent-core/polaris-agent-core-optional-java9/pom.xml
- polaris-agent-core/polaris-agent-core-optional-java9/src/main/java/cn/polarismesh/agent/core/optional9/instrument/JavaLangAccess9.java
- polaris-agent-core/pom.xml
> fix: JDK11场景下，部分类和方法获取失败导致启动失败的问题

- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/serviceregistry/LosslessProxyServiceRegistry.java
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/serviceregistry/RegistryInterceptor.java
Fixes #
fix: lossless plugin base instance port is 0
> fix: lossless plugin base instance port is 0

- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/pom.xml
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/serviceregistry/LosslessProxyServiceRegistry.java
Fixes #
fix: lossless plugin log support ns
> fix: lossless plugin log support ns

- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/pom.xml
- pom.xml
> release 1.6.1.

- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/quickstart-examples/provider/src/main/resources/application.properties
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/CircuitBreakerBeanInjector.java
> fix circuitbreaker

- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/CircuitBreakerBeanInjector.java
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/RpcEnhancementBeanInjector.java
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/ConfigurationParserInterceptor.java
> annotation CircuitBreakerBeanInjector

- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2020-examples/gray-release-examples/service-a/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2020-examples/gray-release-examples/service-b/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2020-examples/gray-release-examples/service-c/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2020-examples/quickstart-examples/consumer/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2020-examples/quickstart-examples/provider/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2021-examples/gray-release-examples/service-a/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2021-examples/gray-release-examples/service-b/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2021-examples/gray-release-examples/service-c/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2021-examples/quickstart-examples/consumer/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2021-examples/quickstart-examples/provider/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/gray-release-examples/service-a/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/gray-release-examples/service-b/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/gray-release-examples/service-c/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/gray-release-examples/service-gateway/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/quickstart-examples/consumer/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/quickstart-examples/provider/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/quickstart-examples/provider/src/main/java/cn/polarismesh/agent/examples/alibaba/cloud/cloud/ProviderApplication.java
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/quickstart-examples/scg/pom.xml
> change version of sca

- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-a/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-b/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-c/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-gateway/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/consumer/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/gateway/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/provider/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/gray-release-examples/service-a/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-hoxton-examples/gray-release-examples/service-b/pom.xml
> fix:fix exampe_build.sh not run,add version of 2023-pom

- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2023-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/MetadataTransferBeanInjector.java
> fix:Full link gray scale in agent2023 not success

- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-a/deployment.yaml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-b/deployment.yaml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-c/deployment.yaml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/gray-release-examples/service-gateway/deployment.yaml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/consumer/deployment.yaml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/gateway/deployment.yaml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/provider/deployment.yaml
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2023-plugin/pom.xml
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2023-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/CommonBeanInjector.java
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2023-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/RegistryBeanInjector.java
- pom.xml
> feat:change version tag and deployment.yml

- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2023-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/RegisterBeanInterceptor.java
Fixes #
fix:fix agent2023 could not start #188
> fix:fix agent2023 could not start

- polaris-agent-core/polaris-agent-core-bootstrap-common/src/main/java/cn/polarismesh/agent/core/bootstrap/PolarisAgentBootStrap.java
- polaris-agent-core/polaris-agent-core-bootstrap-common/src/main/java/cn/polarismesh/agent/core/bootstrap/PolarisInitProperties.java
- polaris-agent-core/polaris-agent-core-bootstrap-common/src/main/java/cn/polarismesh/agent/core/bootstrap/SetProperties.java
> ban nacos registry and config

- polaris-agent-build/bin/start.sh
- polaris-agent-core/polaris-agent-core-asm/src/main/java/cn/polarismesh/agent/core/asm/instrument/plugin/PluginNameFilter.java
- polaris-agent-core/polaris-agent-core-common/src/main/java/cn/polarismesh/agent/core/common/utils/ReflectionUtils.java
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/provider/pom.xml
- polaris-agent-examples/spring-cloud-plugins-examples/spring-cloud-2023-examples/quickstart-examples/provider/src/main/resources/bootstrap.properties
- polaris-agent-plugins/spring-cloud-plugins/spring-cloud-plugin-common/src/main/conf/plugin/spring-cloud/application.properties
- pom.xml
> feat:support spring cloud version auto-detection.
